version: '3'
services:
  proxysql:
    image: 'proxysql/proxysql:latest'
    ports:
      - '6033:6033'
      - '6032:6032'
      - '6080:6080'
    volumes:
      - './proxysql:/var/lib/proxysql'
      - './proxysql.cnf:/etc/proxysql.cnf'
